# ---------------------- 可配置参数 ----------------------
# 1. 路径与基础配置
CLASSES_FILE: "./classes.txt"
OUTPUT_DIR: "./output" # 输出文件夹
IMG_SIZE: [640, 640] # 固定背景尺寸（宽×高）
DATA_NUMBERS: 200 # 通用样本数量（供多个类别复用）

# 3. B/R文件夹样本比例
br_ratio: [5, 5]

# 4. 数据增强参数
ROTATION_ANGLE_RANGE: [-60, 60] # 旋转角度范围（度）
AFFINE_DISTORTION_RANGE: 0.1 # 仿射扭曲幅度（0~0.5）
SCALE_MIN: 0.1 # 最小缩放比例
BLUR_PROBABILITY: 0.9 # 模糊触发概率（0~1，如0.5表示50%概率模糊）
KERNEL_RANGE: [5, 45] # 模糊核大小范围（必须为奇数，核越大模糊越强）
# --------------------------------------------------------------------------

