# ---------------------- 可配置参数 ----------------------
# 1. 路径与基础配置
CLASSES_FILE: "./classes.txt"
OUTPUT_DIR: "./generated" # 输出文件夹
IMG_SIZE: [640, 640] # 固定背景尺寸（宽×高）
DATA_NUMBERS: 200 # 通用样本数量（供多个类别复用）

# 4. 数据增强参数
ROTATION_ANGLE_RANGE: [-60, 60] # 旋转角度范围（度）
AFFINE_DISTORTION_RANGE: 0.1 # 仿射扭曲幅度（0~0.5）
SCALE_MIN: 0.1 # 最小缩放比例
BLUR_PROBABILITY: 0.6 # 模糊触发概率
KERNEL_RANGE: [3, 41] # 模糊核大小范围（必须为奇数，核越大模糊越强）
PERSPECTIVE_RANGE: 0.1 # 透视变换幅度（0~0.5）
# --------------------------------------------------------------------------

